=== EnriqueVergara/TT/TT/DTDOntologia.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT root (concept+)>
<!ELEMENT concept (languaje?, word?, concept*)>
<!ATTLIST concept nombre CDATA #REQUIRED>
<!ELEMENT languaje (#PCDATA)>
<!ELEMENT word (#PCDATA)>

=== EnriqueVergara/TT/TT/prueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "DTDOntologia.dtd">
<root>
	
<concept nombre="entidad">
    <concept nombre="entidad abstracta">
        <concept nombre="atributo">
            <concept nombre="sentimiento">
                <concept nombre="emoción">
                    <concept nombre="felicidad">
                    </concept>
                    <concept nombre="tristeza"></concept>
                </concept>
            </concept>
        </concept>
        <concept nombre="capacidad psicologica">
            <concept nombre="conocimiento">
                <concept nombre="proceso cognitivo">
                    <concept nombre="proceso cognitivo básico">
                        <concept nombre="precepción">
                            <concept nombre="sencación">
                                <concept nombre="experiencia sensorial">
                                    <concept nombre="sabor">
                                    </concept>
                                    <concept nombre="olor">
                                    </concept>
                                </concept>
                            </concept>
                        </concept>
                    </concept>
                </concept>
                <concept nombre="contenido cognitivo">
                    <concept nombre="dominio del conocimiento">
                        <concept nombre="area del conocimiento">
                            <concept nombre="ciencia">
                                <concept nombre="matematicas">
                                </concept>
                            </concept>
                            <concept nombre="ciencias naturales">
                                <concept nombre="biología">
                                </concept>
                                <concept nombre="química">
                                </concept>
                            </concept>
                        </concept>
                    </concept>
                </concept>
            </concept>
        </concept>
    </concept>
    
    <concept nombre="entidad física">
        <languaje>Spanish</languaje>
        <word>Entidad fisica</word>

        <concept nombre="objeto físico">
            <concept nombre="organismo viviente">
                <concept nombre="persona">
                    
                    <concept nombre="trabajador">
                        <concept nombre="empleado">
                        </concept>
                        <concept nombre="trabajador calificado">
                            <concept nombre="militar">
                                <concept nombre="oficial militar">
                                    <concept nombre="general"></concept>
                                    <concept nombre="coronel"></concept>
                                    <concept nombre="oficial mayor"></concept>
                                    <concept nombre="mariscal"></concept>
                                </concept>
                                <concept nombre="enlistado">
                                    <concept nombre="soldado">
                                    </concept>
                                </concept>
                            </concept>
                        </concept>
                    </concept>
                    <concept nombre="amigo"></concept>
                    <concept nombre="familiar">
                        <concept nombre="hermano"></concept>
                        <concept nombre="hermana"></concept>
                        <concept nombre="padre"></concept>
                        <concept nombre="madre"></concept>
                        <concept nombre="tío"></concept>
                        <concept nombre="tía"></concept>
                        <concept nombre="pareja">
                            <concept nombre="novia"></concept>
                            <concept nombre="novio"></concept>
                            <concept nombre="esposo"></concept>
                            <concept nombre="esposa"></concept>
                        </concept>
                    </concept>
                </concept>
            </concept>
            <concept nombre="ubicación">
                <concept nombre="continente">
                    <concept nombre="europa"></concept>
                    <concept nombre="américa"></concept>
                </concept>
                <concept nombre="región">
                    <concept nombre="división territorial">
                        <concept nombre="estado">
                            <concept nombre="oaxaca">
                            </concept>
                            <concept nombre="sonora">                            
                            </concept>                                
                            <concept nombre="hidalgo">                            
                            </concept>    
                            <concept nombre="jalisco">    
                            </concept>    
                        </concept>
                        <concept nombre="país">    
                            <concept nombre="México"></concept>
                        </concept>
                        <concept nombre="población">
                            <concept nombre="municipalidad">
                                <concept nombre="ciudad">
                                    <concept nombre="madrid">
                                    </concept>
                                    <concept nombre="guadalajara">
                                    </concept>                
                                    <concept nombre="df">
                                    </concept>
                                    <concept nombre="guanajuato">
                                    </concept>
                                </concept>
                            </concept>
                        </concept>
                    </concept>
                </concept>
            </concept>
            </concept>
            <concept nombre="mesa"></concept>
            <concept nombre="artefacto">
                <concept nombre="instrumentalidad">
                    <concept nombre="contenedor">
                        <languaje>Spanish</languaje>
                        <word>contenedor</word>
                        <concept nombre="taza">
                            <languaje>Spanish</languaje>
                            <word>taza</word>
                        </concept>
                        <concept nombre="vaso">
                            <languaje>Spanish</languaje>
                            <word>vaso</word>
                        </concept>
                        <concept nombre="olla">
                            <languaje>Spanish</languaje>
                            <word>olla</word>
                        </concept>
                    </concept>
                    <concept nombre="transporte">
                        <concept nombre="vehículo">
                            <concept nombre="navegador">
                                <concept nombre="aéreo">
                                    <concept nombre="avión">
                                    </concept>
                                </concept>
                                <concept nombre="maritimo">
                                    <concept nombre="barco">
                                    </concept>
                                </concept>
                            </concept>
                        </concept>
                        <concept nombre="transporte público">
                            <concept nombre="autobús">
                            </concept>
                            <concept nombre="tren">
                            </concept>
                            <concept nombre="metro">
                            </concept>
                        </concept>
                    </concept>
                </concept>
                <concept nombre="creación">
                    <concept nombre="producto">
                        <concept nombre="trabajo">
                            <concept nombre="publicación">
                                <concept nombre="libro">
                                </concept>
                            </concept>
                        </concept>
                    </concept>
                </concept>
                <concept nombre="herramienta">
                    <concept nombre="herramienta de jardín">
                        <concept nombre="podadora">
                        </concept>
                    </concept>
                </concept>

            </concept>
        <concept nombre="materia">
            <concept nombre="solido">
                <concept nombre="plastico"></concept>
            </concept>
            <concept nombre="fluido">
                <concept nombre="liquido">
                    <concept nombre="agua">
                    </concept>
                </concept>
            </concept>
            <concept nombre="sustancia">
                <concept nombre="material">
                    <concept nombre="planta">
                        <concept nombre="madera"></concept>
                    </concept>
                    <concept nombre="tierra">
                        <concept nombre="suelo">
                            <concept nombre="barro">
                            </concept>
                        </concept>
                    </concept>
                </concept>
                
                <concept nombre="alimento">
                    <concept nombre="productos horneados">
                        <concept nombre="pastelillo">
                            <concept nombre="rosquilla"></concept>
                            <concept nombre="pastel"></concept>
